### PR TITLE
Test

### PR DESCRIPTION
**Pull request by V0pe**
### React Testing Library +  Jest

In this project, we(@maenkhraisha and I did the following to perform automatic testing for the application: 

- [ ] Add the `renderer dependency`
- [ ] Set up the react testing library
- [ ] Test the User interaction
- [ ] Test the operation using `unit tests`
- [ ] Test the components with `snapshot`

### CODE REVIEW

**Review by omar-muhamad — COMMENTED** [review]
# Invalid ❌

Hi Team,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Your Code Review Request is marked as invalid for these reasons:

- [ ] This is supposed to be a collaboration project and I don't see any contribution from @Maen Al-khraisha and all the work is done by @V0pe so Please redo your project and make sure that every partner has an equal amount of work shared and pushed to the working branch.

https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/project_tests.md#work-and-submission-mode

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Review by mikethreels — CHANGES_REQUESTED** [review]
Hi Team, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## Required Changes ♻️
- [ ] according to the requirements you are supposed to write tests for the operate.js and calculate.js files however, there are only tests for the Calculator.js file visible.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by V0pe** [comment]
@mikethreels Thank you for the insight, I have tried creating snapshot for the operate and calculate. There seems to be an issue. But I will adjust accordingly.

**Review by KDlamini — COMMENTED** [review]
## Status: Invalid 🔴 

### Hi @V0pe 🙋‍♀️,  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request
 
You have submitted a project, that has linter checks that do not pass. Please make sure that your project does not have any linter errors before you submit for a review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
 
Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by rotimiazeez — APPROVED** [review]
# Hi TEAM👍🏾, 

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
